In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
data=pd.read_csv('mushrooms.csv')
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [13]:
data.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
mappings = list()
encoder = LabelEncoder()

for column in range(len(data.columns)):
    data[data.columns[column]]=encoder.fit_transform(data[data.columns[column]])
    mappings_dict={index:label for index,label in enumerate (encoder.classes_)}
    mappings.append(mappings_dict)

In [15]:
data.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [50]:
Y=data['class']
X=data.drop('class',axis=1)

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [52]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

X=pd.DataFrame(scalar.fit_transform(X), columns=X.columns)

In [53]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-0.84654963,  0.9504593 ,  1.79845965, ..., -1.09502697,
         1.07975868, -0.29613015],
       [ 1.03000635,  0.9504593 , -0.18431722, ..., -0.25551778,
         1.07975868, -0.29613015],
       [-0.84654963,  0.13732415, -0.5808726 , ..., -0.67527237,
        -2.88490904, -0.29613015],
       ...,
       [ 1.03000635,  0.13732415, -0.5808726 , ..., -0.25551778,
        -0.50610841, -0.29613015],
       [-0.84654963, -1.48894614, -0.18431722, ..., -0.25551778,
         0.28682513, -0.87555243],
       [ 1.03000635,  0.9504593 , -0.5808726 , ..., -0.25551778,
         1.07975868, -0.87555243]])

In [54]:
#fitting gaussian naive bayes to the training set

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)
model.fit(X_train, Y_train)

GaussianNB()

In [61]:
Y_pred=model.predict(x_test)
Y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [70]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
cm
accuracy_score(Y_test,Y_pred)

0.5086164451009355

In [67]:
#Bernoulli
from sklearn.naive_bayes import BernoulliNB
model =  BernoulliNB()
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)
model.fit(X_train, Y_train)

BernoulliNB()

In [68]:
Y_pred=model.predict(x_test)
Y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [69]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
accuracy_score(Y_test,Y_pred)

0.5086164451009355